excluded:
  - Pods
  - sfzfans/Extensions/GoodSwift.swift

opt_in_rules:
  - include-whitespace-only-lines
  - empty_string
  - colon
  - comma
  - array_init
  - attributes
  - first_where
  - vertical_whitespace_between_cases
  - explicit_self
  - yoda_condition
  - unused_import
  - fallthrough
  - flatmap_over_map_reduce
  - unused_declaration
  - force_unwrapping
  - unowned_variable_capture
  - redundant_set_access_control
  - redundant_type_annotation
  - sorted_first_last

custom_rules:

    already_true:
      regex: "== true"
      message: "Don't compare to true, just use the bool value."
    already_bool:
      regex: "== false"
      message: "Don't compare to false, just use !value."    

disabled_rules:
  - identifier_name
  - valid_docs
  - type_name
  - trailing_whitespace
  - unowned_variable_capture

file_length:
  warning: 550
  error: 1200

large_tuple:
   - 4
   - 5

line_length:
    warning: 250
    error: 500
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

cyclomatic_complexity: 12
function_body_length:
    warning: 80
    error: 100
function_parameter_count: 5

type_body_length: 300

reporter: "xcode"
# // swiftlint:disable <rule1>
# // swiftlint:enable <rule1>
